usr/lib/*/libkea-*.so.*
usr/share/man/man8/kea-lfc.8
usr/sbin/kea-lfc
usr/bin/kea-msg-compiler

usr/share/kea/scripts/mysql/dhcpdb_create.mysql
usr/share/kea/scripts/mysql/dhcpdb_drop.mysql
usr/share/kea/scripts/mysql/upgrade_1.0_to_2.0.sh
usr/share/kea/scripts/mysql/upgrade_2.0_to_3.0.sh
usr/share/kea/scripts/mysql/upgrade_3.0_to_4.0.sh
usr/share/kea/scripts/mysql/upgrade_4.0_to_4.1.sh
usr/share/kea/scripts/mysql/upgrade_4.1_to_5.0.sh
usr/share/kea/scripts/mysql/upgrade_5.0_to_5.1.sh
usr/share/kea/scripts/pgsql/dhcpdb_create.pgsql
usr/share/kea/scripts/pgsql/dhcpdb_drop.pgsql
usr/share/kea/scripts/pgsql/upgrade_1.0_to_2.0.sh
usr/share/kea/scripts/pgsql/upgrade_2.0_to_3.0.sh
usr/share/kea/scripts/pgsql/upgrade_3.0_to_3.1.sh
usr/share/kea/scripts/cql/dhcpdb_create.cql
usr/share/kea/scripts/cql/dhcpdb_drop.cql
usr/share/kea/scripts/cql/soft_wipe.cql

usr/share/man/man8/keactrl.8
usr/sbin/keactrl
debian/keactrl.conf             etc/kea
